version: "3.8"

services:
  msw-inventory:
    image: postgres
    container_name: msw-inventory-postgres
    ports:
      - 6500:5432
    restart: always
    env_file:
      - ./.env
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
