[tool.autoflake]
check = true
ignore-init-module-imports = true
in-place = true
recursive = true
remove-all-unused-imports = true
remove-unused-variables = true

[tool.black]
exclude = ".git/,.venv/,.vscode/,logs/,__pycache__,*.md,Dockerfile"
line-length = 100
preview = true
target-version = ["py310", "py311"]

[tool.isort]
extend_skip = [".md"]
import_heading_firstparty = "Project"
import_heading_localfolder = "Local"
import_heading_stdlib = "Standard Library"
import_heading_thirdparty = "External"
line_length = 100
lines_after_imports = 2
multi_line_output = 3
profile = "black"
skip = [".git/", ".venv/", ".vscode/", "logs/", "__pycache__", "Dockerfile"]

[tool.ruff]
line-length = 100
target-version = "py311"
