# Standard Library
import os


VERSION = "0.1.1"
PROJECT_NAME = "msw-inventory"

DATABASE_PORT = os.getenv("DATABASE_PORT", 8080)
POSTGRES_PASSWORD = os.getenv("POSTGRES_PASSWORD")
POSTGRES_USER = os.getenv("POSTGRES_USER", "default_user")
POSTGRES_DB = os.getenv("POSTGRES_DB")
POSTGRES_HOST = os.getenv("POSTGRES_HOST")
POSTGRES_HOSTNAME = os.getenv("POSTGRES_HOSTNAME")

ACCESS_TOKEN_EXPIRES_IN = os.getenv("ACCESS_TOKEN_EXPIRES_IN")
REFRESH_TOKEN_EXPIRES_IN = os.getenv("REFRESH_TOKEN_EXPIRES_IN")
CLIENT_ORIGIN = os.getenv("CLIENT_ORIGIN")

JWT_ALGORITHM = os.getenv("JWT_ALGORITHM", "RS256")
JWT_PRIVATE_KEY = os.getenv("JWT_PRIVATE_KEY", "None")
JWT_PUBLIC_KEY = os.getenv("JWT_PUBLIC_KEY", "None")
